package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private long id;
     private Date fecha;
     private String accion;
     private String modelo;
     private String campo;
     private String campoNuevoValor;
     private Long usuarioId;

    public Auditoria() {
    }

	
    public Auditoria(long id) {
        this.id = id;
    }
    public Auditoria(long id, Date fecha, String accion, String modelo, String campo, String campoNuevoValor, Long usuarioId) {
       this.id = id;
       this.fecha = fecha;
       this.accion = accion;
       this.modelo = modelo;
       this.campo = campo;
       this.campoNuevoValor = campoNuevoValor;
       this.usuarioId = usuarioId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public String getCampoNuevoValor() {
        return this.campoNuevoValor;
    }
    
    public void setCampoNuevoValor(String campoNuevoValor) {
        this.campoNuevoValor = campoNuevoValor;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }




}


