package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * CalificacionRutaTuristica generated by hbm2java
 */
public class CalificacionRutaTuristica  implements java.io.Serializable {


     private long id;
     private Integer calificacion;
     private Long rutaTuristicaId;
     private Long usuarioId;

    public CalificacionRutaTuristica() {
    }

	
    public CalificacionRutaTuristica(long id) {
        this.id = id;
    }
    public CalificacionRutaTuristica(long id, Integer calificacion, Long rutaTuristicaId, Long usuarioId) {
       this.id = id;
       this.calificacion = calificacion;
       this.rutaTuristicaId = rutaTuristicaId;
       this.usuarioId = usuarioId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Long getRutaTuristicaId() {
        return this.rutaTuristicaId;
    }
    
    public void setRutaTuristicaId(Long rutaTuristicaId) {
        this.rutaTuristicaId = rutaTuristicaId;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }




}


