package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Checkin generated by hbm2java
 */
public class Checkin  implements java.io.Serializable {


     private long id;
     private Long eventoId;
     private Long sitioId;
     private Long usuarioId;
     private Date fecha;

    public Checkin() {
    }

	
    public Checkin(long id) {
        this.id = id;
    }
    public Checkin(long id, Long eventoId, Long sitioId, Long usuarioId, Date fecha) {
       this.id = id;
       this.eventoId = eventoId;
       this.sitioId = sitioId;
       this.usuarioId = usuarioId;
       this.fecha = fecha;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Long eventoId) {
        this.eventoId = eventoId;
    }
    public Long getSitioId() {
        return this.sitioId;
    }
    
    public void setSitioId(Long sitioId) {
        this.sitioId = sitioId;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


