package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * ComentarioRutaTuristica generated by hbm2java
 */
public class ComentarioRutaTuristica  implements java.io.Serializable {


     private long id;
     private String comentario;
     private Long rutaTuristicaId;
     private Long usuarioId;

    public ComentarioRutaTuristica() {
    }

	
    public ComentarioRutaTuristica(long id) {
        this.id = id;
    }
    public ComentarioRutaTuristica(long id, String comentario, Long rutaTuristicaId, Long usuarioId) {
       this.id = id;
       this.comentario = comentario;
       this.rutaTuristicaId = rutaTuristicaId;
       this.usuarioId = usuarioId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Long getRutaTuristicaId() {
        return this.rutaTuristicaId;
    }
    
    public void setRutaTuristicaId(Long rutaTuristicaId) {
        this.rutaTuristicaId = rutaTuristicaId;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }




}


