package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * ComentarioSitio generated by hbm2java
 */
public class ComentarioSitio  implements java.io.Serializable {


     private long id;
     private String comentario;
     private Long sitioId;
     private Long usuarioId;

    public ComentarioSitio() {
    }

	
    public ComentarioSitio(long id) {
        this.id = id;
    }
    public ComentarioSitio(long id, String comentario, Long sitioId, Long usuarioId) {
       this.id = id;
       this.comentario = comentario;
       this.sitioId = sitioId;
       this.usuarioId = usuarioId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Long getSitioId() {
        return this.sitioId;
    }
    
    public void setSitioId(Long sitioId) {
        this.sitioId = sitioId;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }




}


