package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private long id;
     private Long sitioId;
     private Long eventoId;
     private String dia;

    public Dia() {
    }

	
    public Dia(long id) {
        this.id = id;
    }
    public Dia(long id, Long sitioId, Long eventoId, String dia) {
       this.id = id;
       this.sitioId = sitioId;
       this.eventoId = eventoId;
       this.dia = dia;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getSitioId() {
        return this.sitioId;
    }
    
    public void setSitioId(Long sitioId) {
        this.sitioId = sitioId;
    }
    public Long getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Long eventoId) {
        this.eventoId = eventoId;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }




}


