package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * EventoCategoriaEvento generated by hbm2java
 */
public class EventoCategoriaEvento  implements java.io.Serializable {


     private long id;
     private Long eventoId;
     private Long categoriaEventoId;

    public EventoCategoriaEvento() {
    }

	
    public EventoCategoriaEvento(long id) {
        this.id = id;
    }
    public EventoCategoriaEvento(long id, Long eventoId, Long categoriaEventoId) {
       this.id = id;
       this.eventoId = eventoId;
       this.categoriaEventoId = categoriaEventoId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Long eventoId) {
        this.eventoId = eventoId;
    }
    public Long getCategoriaEventoId() {
        return this.categoriaEventoId;
    }
    
    public void setCategoriaEventoId(Long categoriaEventoId) {
        this.categoriaEventoId = categoriaEventoId;
    }




}


