package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String descripcion;
     private String lugar;
     private String latitud;
     private String longitud;
     private Long usuarioId;
     private Integer habilitado;
     private Date fecha;
     private Date validez;
     private Date hora;

    public Evento() {
    }

	
    public Evento(long id) {
        this.id = id;
    }
    public Evento(long id, String nombre, String descripcion, String lugar, String latitud, String longitud, Long usuarioId, Integer habilitado, Date fecha, Date validez, Date hora) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.latitud = latitud;
       this.longitud = longitud;
       this.usuarioId = usuarioId;
       this.habilitado = habilitado;
       this.fecha = fecha;
       this.validez = validez;
       this.hora = hora;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public Long getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Integer getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Integer habilitado) {
        this.habilitado = habilitado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getValidez() {
        return this.validez;
    }
    
    public void setValidez(Date validez) {
        this.validez = validez;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


