package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * Foto generated by hbm2java
 */
public class Foto  implements java.io.Serializable {


     private long id;
     private Long eventoId;
     private Long sitioId;
     private Long promocionId;
     private Long rutaTuristicaId;
     private byte[] imagen;

    public Foto() {
    }

	
    public Foto(long id) {
        this.id = id;
    }
    public Foto(long id, Long eventoId, Long sitioId, Long promocionId, Long rutaTuristicaId, byte[] imagen) {
       this.id = id;
       this.eventoId = eventoId;
       this.sitioId = sitioId;
       this.promocionId = promocionId;
       this.rutaTuristicaId = rutaTuristicaId;
       this.imagen = imagen;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Long eventoId) {
        this.eventoId = eventoId;
    }
    public Long getSitioId() {
        return this.sitioId;
    }
    
    public void setSitioId(Long sitioId) {
        this.sitioId = sitioId;
    }
    public Long getPromocionId() {
        return this.promocionId;
    }
    
    public void setPromocionId(Long promocionId) {
        this.promocionId = promocionId;
    }
    public Long getRutaTuristicaId() {
        return this.rutaTuristicaId;
    }
    
    public void setRutaTuristicaId(Long rutaTuristicaId) {
        this.rutaTuristicaId = rutaTuristicaId;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


