package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * HorarioSitio generated by hbm2java
 */
public class HorarioSitio  implements java.io.Serializable {


     private long id;
     private Long diaId;
     private Date horarioApertura;
     private Date horarioCierre;

    public HorarioSitio() {
    }

	
    public HorarioSitio(long id) {
        this.id = id;
    }
    public HorarioSitio(long id, Long diaId, Date horarioApertura, Date horarioCierre) {
       this.id = id;
       this.diaId = diaId;
       this.horarioApertura = horarioApertura;
       this.horarioCierre = horarioCierre;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getDiaId() {
        return this.diaId;
    }
    
    public void setDiaId(Long diaId) {
        this.diaId = diaId;
    }
    public Date getHorarioApertura() {
        return this.horarioApertura;
    }
    
    public void setHorarioApertura(Date horarioApertura) {
        this.horarioApertura = horarioApertura;
    }
    public Date getHorarioCierre() {
        return this.horarioCierre;
    }
    
    public void setHorarioCierre(Date horarioCierre) {
        this.horarioCierre = horarioCierre;
    }




}


