package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * SitioCategoriaSitio generated by hbm2java
 */
public class SitioCategoriaSitio  implements java.io.Serializable {


     private long id;
     private Long categoriaSitioId;
     private Long sitioId;

    public SitioCategoriaSitio() {
    }

	
    public SitioCategoriaSitio(long id) {
        this.id = id;
    }
    public SitioCategoriaSitio(long id, Long categoriaSitioId, Long sitioId) {
       this.id = id;
       this.categoriaSitioId = categoriaSitioId;
       this.sitioId = sitioId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getCategoriaSitioId() {
        return this.categoriaSitioId;
    }
    
    public void setCategoriaSitioId(Long categoriaSitioId) {
        this.categoriaSitioId = categoriaSitioId;
    }
    public Long getSitioId() {
        return this.sitioId;
    }
    
    public void setSitioId(Long sitioId) {
        this.sitioId = sitioId;
    }




}


