package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0



/**
 * Sitio2 generated by hbm2java
 */
public class Sitio2  implements java.io.Serializable {


     private int idSitio;
     private String nombre;
     private String direccion;

    public Sitio2() {
    }

	
    public Sitio2(int idSitio) {
        this.idSitio = idSitio;
    }
    public Sitio2(int idSitio, String nombre, String direccion) {
       this.idSitio = idSitio;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public int getIdSitio() {
        return this.idSitio;
    }
    
    public void setIdSitio(int idSitio) {
        this.idSitio = idSitio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


