package DAO;
// Generated Dec 11, 2014 10:21:29 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String apellido;
     private String email;
     private String latitud;
     private String longitud;
     private Date fecha;
     private byte[] foto;
     private String password;
     private Integer habilitado;
     private Long facebook;

    public Usuario() {
    }

	
    public Usuario(long id) {
        this.id = id;
    }
    public Usuario(long id, String nombre, String apellido, String email, String latitud, String longitud, Date fecha, byte[] foto, String password, Integer habilitado, Long facebook) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.latitud = latitud;
       this.longitud = longitud;
       this.fecha = fecha;
       this.foto = foto;
       this.password = password;
       this.habilitado = habilitado;
       this.facebook = facebook;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Integer habilitado) {
        this.habilitado = habilitado;
    }
    public Long getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(Long facebook) {
        this.facebook = facebook;
    }




}


